title: "[Q&A]: "
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Version, environment, or steps already tried.
    validations:
      required: false
